// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_EGy7pSqU-mrFxwFq1esNc73tcojHxaE',
    appId: '1:441599081402:web:fb5fe2baf6697e5410fb83',
    messagingSenderId: '441599081402',
    projectId: 'to-do-edc1c',
    authDomain: 'to-do-edc1c.firebaseapp.com',
    storageBucket: 'to-do-edc1c.appspot.com',
    measurementId: 'G-9N8V5XTNX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACs2U7ESkMY4-gJRNqNd7XZr0ED5gQ3jQ',
    appId: '1:441599081402:android:134b9886c7424d6210fb83',
    messagingSenderId: '441599081402',
    projectId: 'to-do-edc1c',
    storageBucket: 'to-do-edc1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl7mWqhC6M8pqZuGC7vd3Q7_Ivjew-ImM',
    appId: '1:441599081402:ios:8ee090405d97c7ff10fb83',
    messagingSenderId: '441599081402',
    projectId: 'to-do-edc1c',
    storageBucket: 'to-do-edc1c.appspot.com',
    iosClientId: '441599081402-gsvb9fgng6hla5tf4q3pspq94tfh1211.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl7mWqhC6M8pqZuGC7vd3Q7_Ivjew-ImM',
    appId: '1:441599081402:ios:aa6572b3001f593710fb83',
    messagingSenderId: '441599081402',
    projectId: 'to-do-edc1c',
    storageBucket: 'to-do-edc1c.appspot.com',
    iosClientId: '441599081402-cntc8lvvuj7j8k3vi0d18bmadnptf270.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
